import { ArrowRight, ShieldCheck } from "lucide-react";
import { Link } from "wouter";

type LegalType = "privacy" | "terms" | "cookies";

const content: Record<LegalType, { title: string; intro: string; sections: [string, string][] }> = {
  privacy: { title: "سياسة الخصوصية", intro: "نحترم خصوصيتك ونلتزم بحماية البيانات التي تشاركها عند طلب خدمات المجموعة المثالية.", sections: [["البيانات التي نجمعها", "قد نجمع الاسم والمدينة ونوع الفرن وبيانات التواصل التي تدخلها في نموذج الحجز، وذلك لغرض التواصل وتأكيد الموعد فقط."], ["استخدام البيانات", "نستخدم البيانات للرد على طلبك، تنسيق الزيارة، تحسين تجربة الموقع وقياس أداء الحملات الإعلانية. لا نبيع بياناتك أو نشاركها لأغراض تسويقية غير مرتبطة بالخدمة."], ["الاحتفاظ والأمان", "نحتفظ بالبيانات بالقدر اللازم لخدمة طلبك، ونتخذ إجراءات مناسبة للحد من الوصول غير المصرح به."], ["حقوقك", "يمكنك طلب معرفة البيانات المرتبطة بطلبك أو تصحيحها أو حذفها عبر التواصل معنا على 0509677008."]] },
  terms: { title: "الشروط والأحكام", intro: "باستخدام الموقع أو إرسال نموذج الحجز، فإنك توافق على الشروط التالية.", sections: [["الحجز", "إرسال النموذج هو طلب موعد وليس تأكيدًا نهائيًا. يتم تأكيد الموعد هاتفيًا أو عبر واتساب حسب توفر الفنيين والمنطقة."], ["الأسعار والعروض", "يتم توضيح تكلفة الخدمة والقطع قبل التنفيذ. عرض الخصم 15% يخضع لتاريخ الصلاحية والخدمات المشمولة في الحملة."], ["الضمان", "يتم تحديد مدة ونطاق الضمان بحسب نوع الإصلاح والقطعة، ويشرحها الفني للعميل قبل بدء العمل."], ["الاستخدام المقبول", "يُمنع استخدام الموقع لإرسال بيانات غير صحيحة أو طلبات وهمية أو أي محتوى مخالف للأنظمة المعمول بها."]] },
  cookies: { title: "سياسة ملفات تعريف الارتباط", intro: "نستخدم ملفات تعريف الارتباط وتقنيات مشابهة لتحسين أداء الموقع وفهم تفاعل الزوار.", sections: [["ما هي الكوكيز؟", "هي ملفات صغيرة تُحفظ على جهازك وتساعد الموقع على تذكر بعض التفضيلات وقياس الزيارات."], ["أنواع الاستخدام", "قد نستخدم كوكيز ضرورية لتشغيل الموقع، وملفات قياس وتحليلات عبر Google Tag Manager، وقياس إعلانات عبر Snapchat Pixel عند تفعيلها."], ["التحكم", "يمكنك رفض الكوكيز غير الضرورية من خلال شريط الموافقة أو إعدادات المتصفح. قد يؤثر ذلك على بعض وظائف القياس وليس على إرسال طلب الحجز."], ["التحديثات", "قد نحدّث هذه السياسة عند إضافة أدوات أو خدمات جديدة، وسيظهر تاريخ آخر تحديث في هذه الصفحة."]] },
};

export default function Legal({ type }: { type: LegalType }) {
  const page = content[type];
  return <main dir="rtl" className="min-h-screen bg-[#07111f] px-5 py-10 text-[#f7f2e8] sm:py-16"><div className="mx-auto max-w-3xl"><Link href="/" className="mb-10 inline-flex items-center gap-2 text-sm font-bold text-[#f0ca70]"><ArrowRight size={17} /> العودة للرئيسية</Link><div className="rounded-[2rem] border border-[#d6a944]/25 bg-[#0b1929] p-7 shadow-2xl sm:p-12"><div className="flex h-14 w-14 items-center justify-center rounded-2xl bg-[#d6a944]/10 text-[#f0ca70]"><ShieldCheck size={28} /></div><p className="mt-7 text-sm font-bold tracking-[0.2em] text-[#d6a944]">المجموعة المثالية</p><h1 className="mt-3 text-3xl font-black sm:text-5xl">{page.title}</h1><p className="mt-5 leading-8 text-white/65">{page.intro}</p><div className="mt-10 space-y-7">{page.sections.map(([heading, body]) => <section key={heading}><h2 className="text-xl font-extrabold text-[#f0ca70]">{heading}</h2><p className="mt-2 leading-8 text-white/60">{body}</p></section>)}</div><p className="mt-10 border-t border-white/10 pt-5 text-xs text-white/35">آخر تحديث: 16 سبتمبر 2026</p></div></div></main>;
}
